export const FETCH_MARKET_ASSETS = 'FETCH_MARKET_ASSETS';
export const ADD_MARKET_ASSETS = 'ADD_MARKET_ASSETS';
export const CLEAR_MARKET_ASSETS = 'CLEAR_MARKET_ASSETS';

// Purchase
export const REQUEST_FETCH_PURCHASE_PLANS = 'REQUEST_FETCH_PURCHASE_PLANS';
export const ADD_PURCHASE_PLANS = 'ADD_PURCHASE_PLANS';
export const REQUEST_PURCHASE_PLANS_FAILED = 'REQUEST_PURCHASE_PLANS_FAILED';
export const CLOSE_PURCHASE_PLANS = 'CLOSE_PURCHASE_PLANS';
export const SELECT_PURCHASE_PLAN = 'SELECT_PURCHASE_PLAN';
export const SHOW_PURCHASE_SELECT_SPACE = 'SHOW_PURCHASE_SELECT_SPACE';
export const HIDE_PURCHASE_SELECT_SPACE = 'HIDE_PURCHASE_SELECT_SPACE';
export const REQUEST_FETCH_PURCHASE_SPACES = 'REQUEST_FETCH_PURCHASE_SPACES';
export const UPDATE_PURCHASE_SPACES = 'UPDATE_PURCHASE_SPACES';
export const REQUEST_PURCHASE_SERVICE = 'REQUEST_PURCHASE_SERVICE';
export const SHOW_PURCHASE_COMPLETE_SCREEN = 'SHOW_PURCHASE_COMPLETE_SCREEN';
export const HIDE_PURCHASE_COMPLETE_SCREEN = 'HIDE_PURCHASE_COMPLETE_SCREEN';
