export const SHOW_SEARCH_OVERLAY = 'SHOW_SEARCH_OVERLAY';
export const HIDE_SEARCH_OVERLAY = 'HIDE_SEARCH_OVERLAY';
export const REQUEST_SEARCH = 'REQUEST_SEARCH';
export const UPDATE_APP_SEARCH_RESULTS = 'UPDATE_APP_SEARCH_RESULTS';
export const UPDATE_SPACE_SEARCH_RESULTS = 'UPDATE_SPACE_SEARCH_RESULTS';
export const UPDATE_MARKET_SEARCH_RESULTS = 'UPDATE_MARKET_SEARCH_RESULTS';

// Search Cache
export const INVALIDATE_SEARCH_CACHE = 'INVALIDATE_SEARCH_CACHE';
export const REQUEST_SEARCH_CACHE = 'REQUEST_SEARCH_CACHE';
export const ADD_TO_APP_SEARCH_CACHE = 'ADD_TO_APP_SEARCH_CACHE';
export const ADD_TO_MARKET_SEARCH_CACHE = 'ADD_TO_MARKET_SEARCH_CACHE';
