#osx_image: xcode8.3

matrix:
  include:
    - os: osx
      env: TEST_FILES=BuildTest,extraMetadataTest,globTest,filesTest,ignoreTest,linux.* NODE_VERSION=6

    - os: linux
      env: TEST_FILES=BuildTest,extraMetadataTest,globTest,filesTest,ignoreTest,linux.* NODE_VERSION=6

language: c

cache:
  directories:
    - node_modules
    - packages/electron-builder/node_modules
    - packages/electron-builder-util/node_modules
    - $HOME/.electron
    - /tmp/jest-electron-builder-tests

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L https://dl.bintray.com/develar/bin/7za -o /tmp/7za; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x /tmp/7za; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L https://dl.bintray.com/develar/bin/wine.7z -o /tmp/wine.7z; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /tmp/7za x -o/usr/local/Cellar -y /tmp/wine.7z; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --overwrite fontconfig gd gnutls jasper libgphoto2 libicns libtasn1 libusb libusb-compat little-cms2 nettle openssl sane-backends webp wine git-lfs gnu-tar dpkg xz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install freetype graphicsmagick; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git-lfs pull; fi

install:
- nvm install $NODE_VERSION
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then nvm use --delete-prefix $NODE_VERSION; fi
- npm install -g yarn electron-builder@2.1.1
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm install -g electron-installer-dmg; fi

script:
- yarn
- npm run test
- npm run package:win
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run installer:mac; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then zip -r platmatic-linux.zip ./release/linux-x64; fi

addons:
  artifacts:
    paths:
    - ./platmatic-linux.zip
    - ./platmatic.dmg
