os: unstable
cache:
  - node_modules
environment:
  NSIS_ROOT: C:\nsis
  matrix:
    - nodejs_version: 6
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - 'appveyor DownloadFile "http://sunet.dl.sourceforge.net/project/nsis/NSIS 2/2.46/nsis-2.46-setup.exe" -FileName nsissetup.exe'
  - 'nsissetup.exe /S /D=%NSIS_ROOT%'
  - '%NSIS_ROOT%\makensis'
  - npm install -g yarn electron-builder@2.1.1
  - set PATH=%APPDATA%\npm;%PATH%
  - yarn
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - npm run package:win
  - npm run installer:win
