os: unstable
cache:
  - node_modules
environment:
  NSIS_ROOT: C:\nsis
  matrix:
    - nodejs_version: 6
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - $exePath = "$($env:USERPROFILE)\nsis-2.46-setup.exe"
  - (New-Object Net.WebClient).DownloadFile('http://ufpr.dl.sourceforge.net/project/nsis/NSIS%202/2.46/nsis-2.46-setup.exe', $exePath)
  - cmd /c start /wait $exePath /S /D=C:\nsis
  - npm install -g yarn electron-builder@2.1.1
  - set PATH=%APPDATA%\npm;%PATH%
  - yarn
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - npm run package:win
  - npm run installer:win
