export const FETCH_USERS_IN_ORGANIZATION = 'FETCH_USERS_IN_ORGANIZATION';
export const UPDATE_USERS_IN_ORGANIZATION = 'UPDATE_USERS_IN_ORGANIZATION';
export const CLEAR_USERS_IN_ORGANIZATION = 'CLEAR_USERS_IN_ORGANIZATION';