export const FETCH_SERVICE_INSTANCES_IN_SPACE = 'FETCH_SERVICE_INSTANCES_IN_SPACE';
export const UPDATE_SERVICE_INSTANCES_IN_SPACE = 'UPDATE_SERVICE_INSTANCES_IN_SPACE';
export const FETCH_SERVICE_INSTANCES_FAILED = 'FETCH_SERVICE_INSTANCES_FAILED';
export const DELETE_SERVICE_INSTANCES_FROM_SPACE = 'DELETE_SERVICE_INSTANCES_FROM_SPACE';
export const DELETE_SERVICE_INSTANCE_COMPLETE = 'DELETE_SERVICE_INSTANCE_COMPLETE';
export const DELETE_SERVICE_INSTANCE_FAILED = 'DELETE_SERVICE_INSTANCE_FAILED';
export const CLEAR_SERVICE_INSTANCES = 'CLEAR_SERVICE_INSTANCES';
