export const SELECT_TARGET_DIRECTORY = 'SELECT_TARGET_DIRECTORY';
export const SHOW_CREATE_APP_DIALOG = 'SHOW_CREATE_APP_DIALOG';
export const HIDE_CREATE_APP_DIALOG = 'HIDE_CREATE_APP_DIALOG';
export const REQUEST_CREATE_APP = 'REQUEST_CREATE_APP';
export const APP_INITIALIZATION_SUCCESS = 'APP_INITIALIZATION_SUCCESS';
export const APP_INITIALIZATION_FAILED = 'APP_INITIALIZATION_FAILED';

// Create App Form
export const REQUEST_POPULATE_CREATE_APP_FORM = 'REQUEST_POPULATE_CREATE_APP_FORM';
export const POPULATE_FORM_SPACES = 'POPULATE_FORM_SPACES';
export const POPULATE_FORM_STACKS = 'POPULATE_FORM_STACKS';
export const POPULATE_FORM_SUCCESS = 'POPULATE_FORM_SUCCESS';
export const POPULATE_FORM_BUILDPACKS = 'POPULATE_FORM_BUILDPACKS';
export const POPULATE_FORM_DOMAINS = 'POPULATE_FORM_DOMAINS';
export const POPULATE_FORM_FAILED = 'POPULATE_FORM_FAILED';
