export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGGED_IN = 'LOGGED_IN';
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const LOGGED_OUT = 'LOGGED_OUT';
export const INVALID_LOGIN = 'INVALID_LOGIN';
export const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const TOKEN_REFRESHED = 'TOKEN_REFRESHED';
export const REQUEST_GET_SETTINGS = 'REQUEST_GET_SETTINGS';
export const RETRIEVED_SETTINGS = 'RETRIEVED_SETTINGS';

// Instances
export const OPEN_ADD_CF_INSTANCE_DIALOG = 'OPEN_ADD_CF_INSTANCE_DIALOG';
export const CLOSE_ADD_CF_INSTANCE_DIALOG = 'CLOSE_ADD_CF_INSTANCE_DIALOG';
export const ADD_CF_INSTANCE = 'ADD_CF_INSTANCE';
export const ADD_CF_INSTANCE_SUCCESS = 'ADD_CF_INSTANCE_SUCCESS';
export const ADD_CF_INSTANCE_FAILED = 'ADD_CF_INSTANCE_FAILED';


