export const FETCH_ORGANIZATIONS = 'FETCH_ORGANIZATIONS';
export const UPDATE_ORGANIZATIONS = 'UPDATE_ORGANIZATIONS';
export const CLEAR_ORGANIZATIONS = 'CLEAR_ORGANIZATIONS';
export const FETCH_ORGANIZATION_SUMMARY = 'FETCH_ORGANIZATION_SUMMARY';
export const UPDATE_ORGANIZATION_SUMMARY = 'UPDATE_ORGANIZATION_SUMMARY';
